#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use Autopilot\Apps\TextEditor;
use Autopilot\ProjectClassifier;
use Autopilot\Repository;
use Composer\InstalledVersions;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use Symfony\Component\Console\Style\SymfonyStyle;

$version = InstalledVersions::getPrettyVersion('robbin/autopilot');

(new SingleCommandApplication())
    ->setName('Autopilot')
    ->setVersion($version)
    ->addArgument('repo-url', InputArgument::REQUIRED, 'The URL of repository to review')
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($version) {
        $io = new SymfonyStyle($input, $output);
        $io->title("Autopilot - $version");

        $io->writeln("Cloning repository...");
        $repo = new Repository($input->getFirstArgument());
        $repo->clone();

        $driver = (new ProjectClassifier($repo))->selectDriver();
        $type = (new ReflectionClass($driver))->getShortName();

        $io->writeln("Identified project type: <options=bold>{$type}</>");

        // @todo allow user to select program
        $io->writeln('Opening text editor');
        (new TextEditor("code"))->open($repo->dir()->getPath());

        $driver->setUp();

        $io->section('Serving application');
        $driver->serve();
    })
    ->run();
